server:
  port: 8085

spring:
  application:
    name: API-GATEWAY

#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: HOTEL
#          uri: localhost:8082
#          predicates:
#            - Path=/hotel/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
